### ISSUE TITLE
Mocap c3d to SPML-H / SMPL-X

### ISSUE THREAD

**Issue by xiaohu-art** [LvXinTao/Mocap-to-SMPLX#1]
Hello, appreciate your job but I don't know how to convert the mocap data *.c3d file to *.npz or *.pt file introduced in your Readme. Thank you very much!

**Comment by LvXinTao** [comment]
Currently we don't support Markers->SMPL-X. But you can refer to [MoSh++](https://github.com/nghorbani/moshpp) for the mocap solving.
